<?php

$products = [
	1 => [
		'name' => 'Lyon', 
		'category' => 'woman',
		'brand' => 'Matisse',
		'price' => '129.99',
		'image' => 'catalog/woman/1.jpg',
		'color' => 'Natural Suede',

	],
	2 => [
		'name' => 'Irenee Sandal', 
		'category' => 'woman',
		'brand' => 'Steve Madden',
		'price' => '57.37',
		'image' => 'catalog/woman/2.jpg',
		'color' => 'Blush Patent',
	],
	3 => [
		'name' => 'Court Lite 2', 
		'category' => 'woman',
		'brand' => 'Nike',
		'price' => '48.75',
		'image' => 'catalog/woman/3.jpg',
		'color' => 'White/Photon Dust/Echo Pink',
	],
	4 => [
		'name' => 'Beale', 
		'category' => 'woman',
		'brand' => 'Naturalizer',
		'price' => '99.99',
		'image' => 'catalog/woman/4.jpg',
		'color' => 'White Pebble',
	],
	5 => [
		'name' => 'Noles', 
		'category' => 'woman',
		'brand' => 'Dolce Vita',
		'price' => '85.95',
		'image' => 'catalog/woman/5.jpg',
		'color' => 'White Leather',
	],
	6 => [
		'name' => 'Yaro Ankle Strap Sandal Heel', 
		'category' => 'woman',
		'brand' => 'Sam Edelman',
		'price' => '59.96',
		'image' => 'catalog/woman/6.jpg',
		'color' => 'Electric Pink Neon',
	],
	7 => [
		'name' => 'Gramercy Cap Toe Oxford', 
		'category' => 'man',
		'brand' => 'Cole Haan',
		'price' => '150.0',
		'image' => 'catalog/man/1.jpg',
		'color' => 'British Tan',
	],
	8 => [
		'name' => 'Warren Cap Ox', 
		'category' => 'man',
		'brand' => 'Cole Haan',
		'price' => '200.0',
		'image' => 'catalog/man/2.jpg',
		'color' => 'Black',
	],
	9 => [
		'name' => 'Zerogrand Wing Ox', 
		'category' => 'man',
		'brand' => 'Cole Haan',
		'price' => '114.0',
		'image' => 'catalog/man/3.jpg',
		'color' => 'Burnished British Tan',
	],
	10 => [
		'name' => 'Gold Cup A/O 2-Eye Seaside', 
		'category' => 'man',
		'brand' => 'Sperry',
		'price' => '119.96',
		'image' => 'catalog/man/4.jpg',
		'color' => 'Stern',
	],
	11 => [
		'name' => 'Morris Wing Oxford', 
		'category' => 'man',
		'brand' => 'Cole Haan',
		'price' => '119.97',
		'image' => 'catalog/man/5.jpg',
		'color' => 'British Tan',
	],
	12 => [
		'name' => 'Air Monarch IV', 
		'category' => 'man',
		'brand' => 'Nike',
		'price' => '52.50',
		'image' => 'catalog/man/6.jpg',
		'color' => 'Black',
	],
	13 => [
		'name' => '133033 (Infant/Toddler)', 
		'category' => 'children',
		'brand' => 'Cienta Kids Shoes',
		'price' => '27.20',
		'image' => 'catalog/children/1.jpg',
		'color' => 'Black',
	],
	14 => [
		'name' => '455v2 (Little Kid/Big Kid)', 
		'category' => 'children',
		'brand' => 'New Balance Kids',
		'price' => '44.99',
		'image' => 'catalog/children/2.jpg',
		'color' => 'Bali Blue/Tie-Dye',
	],
	15 => [
		'name' => 'Air Max Excee (Infant/Toddler)', 
		'category' => 'children',
		'brand' => 'Nike Kids',
		'price' => '60.00',
		'image' => 'catalog/children/3.jpg',
		'color' => 'White/University/Blue/Track Red',
	],
	16 => [
		'name' => 'Unleash 2 Speed Texapore Low (Little Kid/Big Kid)', 
		'category' => 'children',
		'brand' => 'Jack Wolfskin Kids',
		'price' => '89.95',
		'image' => 'catalog/children/4.jpg',
		'color' => 'Lime/Dark Green',
	],
	17 => [
		'name' => '2750 JCOT Classic (Toddler/Little Kid)', 
		'category' => 'children',
		'brand' => 'Superga Kids',
		'price' => '33.00',
		'image' => 'catalog/children/5.jpg',
		'color' => 'Melon',
	],
	18 => [
		'name' => 'Lima (Infant/Toddler)', 
		'category' => 'children',
		'brand' => 'TOMS Kids',
		'price' => '27.95',
		'image' => 'catalog/children/6.jpg',
		'color' => 'Red/Blue Canvas',
	],
	
];
